#!/usr/bin/env python
import sys
import os
from rosparam_handler.parameter_generator_catkin import YamlGenerator

if len(sys.argv) < 2:
    sys.exit('Usage: %s <.params file>' % sys.argv[0])

if not os.path.exists(sys.argv[1]):
    sys.exit('ERROR: Param file %s was not found!' % sys.argv[1])

# Read argument
inFile = sys.argv[1] # "/home/claudio/Documents/repos/GitHub/rosparam_ws/src/rosparam_handler/test/cfg/Defaults.params"
# Mock call arguments for call to ParamGenerator
sys.argv[1:4] = ["", "", "", ""]
# Redirect import statement
sys.modules['rosparam_handler.parameter_generator_catkin'] = __import__('sys')

# Execute param file in mocked environment
globalVars = {"__file__": inFile, 'ParameterGenerator': YamlGenerator}
execfile(inFile, globalVars)
